[ 2025-03-02 10:07:46,071 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 10:07:46,091 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 10:07:46,091 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 10:07:46,105 ] 28 root - INFO - Creating new features...
[ 2025-03-02 10:07:46,113 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 10:07:46,524 ] 32 root - ERROR - \u274c Error loading object from artifacts/best_model.pkl: No module named '_loss'
[ 2025-03-02 10:07:46,524 ] 33 root - ERROR - \u274c Failed to load model: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']
[ 2025-03-02 10:07:46,524 ] 63 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [29] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']]
[ 2025-03-02 10:07:46,525 ] 59 root - ERROR - \u274c Model prediction failed: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [48] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [29] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']]]
[ 2025-03-02 10:07:46,525 ] 84 root - ERROR - \u274c Client Error: Prediction error.
[ 2025-03-02 10:16:13,039 ] 76 root - INFO - Loading dataset...
[ 2025-03-02 10:16:13,041 ] 100 root - INFO - Applying data transformations...
[ 2025-03-02 10:16:13,041 ] 16 root - INFO - Performing data cleaning...
[ 2025-03-02 10:16:13,046 ] 28 root - INFO - Creating new features...
[ 2025-03-02 10:16:13,050 ] 39 root - INFO - Encoding and standardizing data...
[ 2025-03-02 10:16:13,116 ] 32 root - ERROR - \u274c Error loading object from artifacts/best_model.pkl: No module named '_loss'
[ 2025-03-02 10:16:13,117 ] 33 root - ERROR - \u274c Failed to load model: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']
[ 2025-03-02 10:16:13,117 ] 63 root - ERROR - \u274c Error during prediction: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [29] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']]
[ 2025-03-02 10:16:13,117 ] 59 root - ERROR - \u274c Model prediction failed: Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [48] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\pipelines\prediction_pipeline.py] line number [29] error message[Error occured in python script name [E:\all projects\Machine Learning Projects\Suppervised Project\Reggration Projects\Big_mart_sales\src\big_mart_sales\utils.py] line number [29] error message[No module named '_loss']]]
[ 2025-03-02 10:16:13,117 ] 84 root - ERROR - \u274c Client Error: Prediction error.
